// core/tools/lib/completion.mjs — shell completion for the my-blog-dlc CLI.
//
// The engine owns state; this module only describes the command surface so a
// shell can offer contextual completions. Scripts are generated on demand from
// the live methodology, so newly added stages and scopes appear automatically.

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { MODES } from "./config.mjs";

export const SUPPORTED_SHELLS = ["bash", "zsh", "fish", "powershell"];

const MARKER_START = "# >>> my-blog-dlc completion >>>";
const MARKER_END = "# <<< my-blog-dlc completion <<<";

const COMMANDS = [
  "config",
  "init",
  "doctor",
  "status",
  "list",
  "stage",
  "scope",
  "phase",
  "graph",
  "orchestrate",
  "completion",
  "version",
  "help",
];

const GLOBAL_FLAGS = ["--json", "--help", "--version", "--project", "--status", "--doctor", "--config"];

const LIST_TARGETS = ["phases", "stages", "scopes", "agents"];
const ORCHESTRATE_VERBS = ["next", "report", "park"];
const COMPLETION_ACTIONS = ["install", "uninstall", "status", ...SUPPORTED_SHELLS];
const REPORT_RESULTS = [
  "in-progress",
  "awaiting-approval",
  "approved",
  "rejected",
  "revised",
  "completed",
  "skipped",
];

/** Detect the user's shell from $SHELL, or null when it cannot be determined. */
export function detectShell(env = process.env) {
  const shell = (env.SHELL || "").split("/").pop().toLowerCase();
  if (!shell) return null;
  if (shell.includes("zsh")) return "zsh";
  if (shell.includes("bash")) return "bash";
  if (shell.includes("fish")) return "fish";
  if (shell.includes("pwsh") || shell.includes("powershell")) return "powershell";
  return null;
}

/** Build the completion vocabulary from the loaded methodology. */
export function buildCompletionModel(methodology, harnesses = [], command = "my-blog-dlc") {
  const phases = methodology.phases.map((phase) => phase.slug);
  const stages = methodology.stages.map((stage) => stage.slug);
  const scopes = methodology.scopes.map((scope) => scope.name);
  const agents = methodology.agents.map((agent) => agent.slug);
  return {
    command,
    commands: [...COMMANDS],
    globalFlags: [...GLOBAL_FLAGS],
    groups: {
      list: [...LIST_TARGETS],
      orchestrate: [...ORCHESTRATE_VERBS],
      completion: [...COMPLETION_ACTIONS],
    },
    options: {
      config: ["--harness", "--project", "--json", "--mode", "--questions-min", "--questions-max"],
      next: ["--new-intent", "--scope", "--resume"],
      report: ["--stage", "--result", "--user-input", "--reason"],
      completion: ["--shell", "--dir", "--no-rc"],
    },
    values: {
      "--harness": [...harnesses],
      "--shell": [...SUPPORTED_SHELLS],
      "--mode": [...MODES],
      "--scope": scopes,
      "--stage": stages,
      "--result": [...REPORT_RESULTS],
    },
    list: { phases, stages, scopes, agents },
  };
}

/** Generate the completion script for a shell. */
export function completionScript(shell, model) {
  switch (shell) {
    case "bash":
      return bashScript(model);
    case "zsh":
      return zshScript(model);
    case "fish":
      return fishScript(model);
    case "powershell":
      return powershellScript(model);
    default:
      throw new Error(`Unsupported shell "${shell}". Use: ${SUPPORTED_SHELLS.join(", ")}.`);
  }
}

// ---------------------------------------------------------------------------
// Per-shell generators
// ---------------------------------------------------------------------------

const fnName = (command) => `_${command.replace(/[^a-zA-Z0-9_]/g, "_")}_complete`;
const words = (list) => list.join(" ");

function bashScript(model) {
  const name = fnName(model.command);
  const values = model.values;
  return `# ${model.command} completion for bash
# Generated by \`${model.command} completion bash\`. Do not edit by hand.

${name}() {
  local cur prev cmd sub
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  local commands="${words(model.commands)}"
  local global_flags="${words(model.globalFlags)}"
  local stages="${words(model.list.stages)}"
  local phases="${words(model.list.phases)}"
  local scopes="${words(model.list.scopes)}"
  local agents="${words(model.list.agents)}"
  local harnesses="${words(values["--harness"])}"
  local shells="${words(values["--shell"])}"
  local results="${words(values["--result"])}"
  local modes="${words(values["--mode"])}"

  case "$prev" in
    --harness) COMPREPLY=($(compgen -W "$harnesses" -- "$cur")); return 0 ;;
    --shell) COMPREPLY=($(compgen -W "$shells" -- "$cur")); return 0 ;;
    --mode) COMPREPLY=($(compgen -W "$modes" -- "$cur")); return 0 ;;
    --scope) COMPREPLY=($(compgen -W "$scopes" -- "$cur")); return 0 ;;
    --stage) COMPREPLY=($(compgen -W "$stages" -- "$cur")); return 0 ;;
    --result) COMPREPLY=($(compgen -W "$results" -- "$cur")); return 0 ;;
    --project) COMPREPLY=($(compgen -d -- "$cur")); return 0 ;;
  esac

  local positionals=()
  local i word
  for ((i = 1; i < COMP_CWORD; i++)); do
    word="\${COMP_WORDS[i]}"
    case "$word" in
      -*) ;;
      *) positionals+=("$word") ;;
    esac
  done
  cmd="\${positionals[0]:-}"
  sub="\${positionals[1]:-}"

  case "$cmd" in
    "")
      COMPREPLY=($(compgen -W "$commands $global_flags" -- "$cur")) ;;
    orchestrate)
      if [ -z "$sub" ]; then
        COMPREPLY=($(compgen -W "${words(model.groups.orchestrate)}" -- "$cur"))
      else
        case "$sub" in
          next) COMPREPLY=($(compgen -W "${words(model.options.next)} $global_flags" -- "$cur")) ;;
          report) COMPREPLY=($(compgen -W "${words(model.options.report)} $global_flags" -- "$cur")) ;;
          *) COMPREPLY=($(compgen -W "$global_flags" -- "$cur")) ;;
        esac
      fi ;;
    list)
      COMPREPLY=($(compgen -W "${words(model.groups.list)} $global_flags" -- "$cur")) ;;
    completion)
      if [ -z "$sub" ]; then
        COMPREPLY=($(compgen -W "${words(model.groups.completion)}" -- "$cur"))
      else
        COMPREPLY=($(compgen -W "${words(model.options.completion)} $global_flags" -- "$cur"))
      fi ;;
    stage)
      COMPREPLY=($(compgen -W "$stages $global_flags" -- "$cur")) ;;
    phase)
      COMPREPLY=($(compgen -W "$phases $global_flags" -- "$cur")) ;;
    scope)
      COMPREPLY=($(compgen -W "$scopes $global_flags" -- "$cur")) ;;
    config)
      COMPREPLY=($(compgen -W "${words(model.options.config)}" -- "$cur")) ;;
    *)
      COMPREPLY=($(compgen -W "$global_flags" -- "$cur")) ;;
  esac
  return 0
}

complete -F ${name} ${model.command}
`;
}

function zshScript(model) {
  const cmd = model.command;
  const fn = `_${cmd}`;
  return `#compdef ${cmd}
# ${cmd} completion for zsh
# Generated by \`${cmd} completion zsh\`. Do not edit by hand.

${fn}() {
  local -a commands global_flags stages phases scopes agents harnesses shells results modes
  commands=(${words(model.commands)})
  global_flags=(${words(model.globalFlags)})
  stages=(${words(model.list.stages)})
  phases=(${words(model.list.phases)})
  scopes=(${words(model.list.scopes)})
  agents=(${words(model.list.agents)})
  harnesses=(${words(model.values["--harness"])})
  shells=(${words(model.values["--shell"])})
  results=(${words(model.values["--result"])})
  modes=(${words(model.values["--mode"])})

  local prev cmd sub
  prev=\${words[CURRENT-1]}
  cmd=\${words[2]}
  sub=\${words[3]}

  case $prev in
    --harness) compadd -- $harnesses; return ;;
    --shell) compadd -- $shells; return ;;
    --scope) compadd -- $scopes; return ;;
    --stage) compadd -- $stages; return ;;
    --result) compadd -- $results; return ;;
    --mode) compadd -- $modes; return ;;
    --project) _path_files -/; return ;;
  esac

  if (( CURRENT == 2 )); then
    compadd -- $commands $global_flags
    return
  fi

  case $cmd in
    orchestrate)
      if (( CURRENT == 3 )); then compadd -- ${words(model.groups.orchestrate)}; return; fi
      case $sub in
        next) compadd -- ${words(model.options.next)} $global_flags ;;
        report) compadd -- ${words(model.options.report)} $global_flags ;;
        *) compadd -- $global_flags ;;
      esac ;;
    list) compadd -- ${words(model.groups.list)} $global_flags ;;
    completion)
      if (( CURRENT == 3 )); then compadd -- ${words(model.groups.completion)}; return; fi
      compadd -- ${words(model.options.completion)} $global_flags ;;
    stage) compadd -- $stages $global_flags ;;
    phase) compadd -- $phases $global_flags ;;
    scope) compadd -- $scopes $global_flags ;;
    config) compadd -- ${words(model.options.config)} ;;
    *) compadd -- $global_flags ;;
  esac
}

if (( $+functions[compdef] )); then
  compdef ${fn} ${cmd}
fi
`;
}

function fishScript(model) {
  const cmd = model.command;
  const lines = [
    `# ${cmd} completion for fish`,
    `# Generated by \`${cmd} completion fish\`. Do not edit by hand.`,
    "",
    `complete -c ${cmd} -f`,
    "",
  ];

  for (const name of model.commands) {
    lines.push(
      `complete -c ${cmd} -n "__fish_use_subcommand" -a "${name}"`,
    );
  }
  lines.push("");
  lines.push(
    `complete -c ${cmd} -n "__fish_seen_subcommand_from orchestrate" -a "${words(model.groups.orchestrate)}"`,
  );
  lines.push(`complete -c ${cmd} -n "__fish_seen_subcommand_from list" -a "${words(model.groups.list)}"`);
  lines.push(
    `complete -c ${cmd} -n "__fish_seen_subcommand_from completion" -a "${words(model.groups.completion)}"`,
  );
  lines.push(
    `complete -c ${cmd} -n "__fish_seen_subcommand_from stage" -a "${words(model.list.stages)}"`,
  );
  lines.push(
    `complete -c ${cmd} -n "__fish_seen_subcommand_from phase" -a "${words(model.list.phases)}"`,
  );
  lines.push(
    `complete -c ${cmd} -n "__fish_seen_subcommand_from scope" -a "${words(model.list.scopes)}"`,
  );
  lines.push("");
  lines.push(`complete -c ${cmd} -l json -d "Machine-readable output"`);
  lines.push(`complete -c ${cmd} -l harness -x -a "${words(model.values["--harness"])}"`);
  lines.push(`complete -c ${cmd} -l scope -x -a "${words(model.values["--scope"])}"`);
  lines.push(`complete -c ${cmd} -l stage -x -a "${words(model.values["--stage"])}"`);
  lines.push(`complete -c ${cmd} -l result -x -a "${words(model.values["--result"])}"`);
  lines.push(`complete -c ${cmd} -l mode -x -a "${words(model.values["--mode"])}"`);
  lines.push(`complete -c ${cmd} -l shell -x -a "${words(model.values["--shell"])}"`);
  lines.push(`complete -c ${cmd} -l new-intent -d "Start a new intent"`);
  lines.push(`complete -c ${cmd} -l resume -d "Resume a parked workflow"`);
  lines.push(`complete -c ${cmd} -l user-input -x -d "Human input to record"`);
  lines.push(`complete -c ${cmd} -l reason -x -d "Reason for the report"`);
  lines.push(`complete -c ${cmd} -l project -x -a "(__fish_complete_directories)"`);
  lines.push("");
  return lines.join("\n");
}

function powershellScript(model) {
  const cmd = model.command;
  const psArray = (list) => `@(${list.map((item) => `'${item.replace(/'/g, "''")}'`).join(", ")})`;
  return `# ${cmd} completion for PowerShell
# Generated by \`${cmd} completion powershell\`. Do not edit by hand.

Register-ArgumentCompleter -Native -CommandName ${cmd} -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)

  $commands = ${psArray(model.commands)}
  $globalFlags = ${psArray(model.globalFlags)}
  $listTargets = ${psArray(model.groups.list)}
  $verbs = ${psArray(model.groups.orchestrate)}
  $completionActions = ${psArray(model.groups.completion)}
  $harnesses = ${psArray(model.values["--harness"])}
  $shells = ${psArray(model.values["--shell"])}
  $scopes = ${psArray(model.values["--scope"])}
  $stages = ${psArray(model.values["--stage"])}
  $results = ${psArray(model.values["--result"])}
  $modes = ${psArray(model.values["--mode"])}

  $elements = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })
  $positionals = @()
  foreach ($element in $elements) {
    if ($element -notlike '-*') { $positionals += $element }
  }

  $prev = $null
  if ($elements.Count -ge 2) { $prev = $elements[$elements.Count - 1].ToString() }

  $candidates = @()
  switch ($prev) {
    '--harness' { $candidates = $harnesses }
    '--shell' { $candidates = $shells }
    '--scope' { $candidates = $scopes }
    '--stage' { $candidates = $stages }
    '--result' { $candidates = $results }
    '--mode' { $candidates = $modes }
    default {
      $cmd = if ($positionals.Count -ge 2) { $positionals[1] } else { '' }
      $sub = if ($positionals.Count -ge 3) { $positionals[2] } else { '' }
      switch ($cmd) {
        '' { $candidates = $commands + $globalFlags }
        'orchestrate' {
          if ($sub) { $candidates = $globalFlags }
          else { $candidates = $verbs }
        }
        'list' { $candidates = $listTargets + $globalFlags }
        'completion' {
          if ($sub) { $candidates = @('--shell', '--dir', '--no-rc') + $globalFlags }
          else { $candidates = $completionActions }
        }
        'stage' { $candidates = $stages + $globalFlags }
        'phase' { $candidates = $stages + $globalFlags }
        'scope' { $candidates = $scopes + $globalFlags }
        'config' { $candidates = @('--harness', '--project', '--json', '--mode', '--questions-min', '--questions-max') }
        default { $candidates = $globalFlags }
      }
    }
  }

  $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
  }
}
`;
}

// ---------------------------------------------------------------------------
// Installation
// ---------------------------------------------------------------------------

function powershellProfile(home, xdgConfig) {
  const configRoot = xdgConfig || join(home, ".config");
  return join(configRoot, "powershell", "Microsoft.PowerShell_profile.ps1");
}

/** Resolve where a shell's completion script should live. */
export function completionTarget(shell, options = {}) {
  const home = options.home || homedir();
  const xdgData = options.xdgData || process.env.XDG_DATA_HOME || join(home, ".local", "share");
  const xdgConfig = options.xdgConfig || process.env.XDG_CONFIG_HOME || join(home, ".config");
  const dir = options.dir;
  const rcPath = options.rcPath;

  switch (shell) {
    case "bash":
      return {
        scriptPath: dir ? join(dir, "my-blog-dlc.bash") : join(xdgData, "my-blog-dlc", "completions", "my-blog-dlc.bash"),
        rcPath: rcPath || join(home, ".bashrc"),
      };
    case "zsh":
      return {
        scriptPath: dir ? join(dir, "_my-blog-dlc") : join(xdgData, "my-blog-dlc", "completions", "_my-blog-dlc"),
        rcPath: rcPath || join(home, ".zshrc"),
      };
    case "fish":
      return {
        scriptPath: dir ? join(dir, "my-blog-dlc.fish") : join(xdgConfig, "fish", "completions", "my-blog-dlc.fish"),
        rcPath: null,
      };
    case "powershell":
      return {
        scriptPath: dir ? join(dir, "my-blog-dlc.ps1") : join(xdgConfig, "powershell", "my-blog-dlc-completion.ps1"),
        rcPath: rcPath || powershellProfile(home, xdgConfig),
      };
    default:
      throw new Error(`Unsupported shell "${shell}". Use: ${SUPPORTED_SHELLS.join(", ")}.`);
  }
}

function rcBlockFor(shell, scriptPath) {
  if (shell === "bash") {
    return `${MARKER_START}\n[ -f "${scriptPath}" ] && . "${scriptPath}"\n${MARKER_END}`;
  }
  if (shell === "zsh") {
    return `${MARKER_START}\n[ -f "${scriptPath}" ] && source "${scriptPath}"\n${MARKER_END}`;
  }
  if (shell === "powershell") {
    return `${MARKER_START}\nif (Test-Path "${scriptPath}") { . "${scriptPath}" }\n${MARKER_END}`;
  }
  return null;
}

function upsertBlock(file, block) {
  let text = existsSync(file) ? readFileSync(file, "utf8") : "";
  const startIdx = text.indexOf(MARKER_START);
  if (startIdx !== -1) {
    const endIdx = text.indexOf(MARKER_END, startIdx);
    const head = text.slice(0, startIdx);
    const tail = endIdx === -1 ? "" : text.slice(endIdx + MARKER_END.length).replace(/^\n+/, "");
    const next = `${head}${block}\n${tail}`;
    if (next === text) return false;
    writeFileSync(file, next, "utf8");
    return true;
  }
  if (text.length > 0 && !text.endsWith("\n")) text += "\n";
  const separator = text.length > 0 ? "\n" : "";
  writeFileSync(file, `${text}${separator}${block}\n`, "utf8");
  return true;
}

/** Write a completion script and wire it into the shell's rc file. */
export function installCompletion({ shell, model, home, xdgData, xdgConfig, dir, rcPath, noRc = false }) {
  const target = completionTarget(shell, { home, xdgData, xdgConfig, dir, rcPath });
  mkdirSync(dirname(target.scriptPath), { recursive: true });
  writeFileSync(target.scriptPath, completionScript(shell, model), "utf8");

  let rcUpdated = false;
  const block = target.rcPath ? rcBlockFor(shell, target.scriptPath) : null;
  if (!noRc && target.rcPath && block) {
    mkdirSync(dirname(target.rcPath), { recursive: true });
    rcUpdated = upsertBlock(target.rcPath, block);
  }
  return {
    shell,
    scriptPath: target.scriptPath,
    rcPath: target.rcPath,
    rcUpdated,
    rcManaged: !noRc && Boolean(target.rcPath),
  };
}

/** Report whether an installed completion script matches the current engine. */
export function completionStatus({ shell, model, home, xdgData, xdgConfig, dir, rcPath }) {
  const target = completionTarget(shell, { home, xdgData, xdgConfig, dir, rcPath });
  const installed = existsSync(target.scriptPath);
  let upToDate = false;
  if (installed) {
    upToDate = readFileSync(target.scriptPath, "utf8") === completionScript(shell, model);
  }
  const rcWired =
    Boolean(target.rcPath) && existsSync(target.rcPath)
      ? readFileSync(target.rcPath, "utf8").includes(target.scriptPath)
      : false;
  return {
    shell,
    installed,
    upToDate,
    stale: installed && !upToDate,
    scriptPath: target.scriptPath,
    rcPath: target.rcPath,
    rcWired,
  };
}

/** Remove a completion script and its managed rc block. */
export function uninstallCompletion({ shell, home, xdgData, xdgConfig, dir, rcPath }) {
  const target = completionTarget(shell, { home, xdgData, xdgConfig, dir, rcPath });
  let removedScript = false;
  if (existsSync(target.scriptPath)) {
    rmSync(target.scriptPath, { force: true });
    removedScript = true;
  }

  let rcUpdated = false;
  if (target.rcPath && existsSync(target.rcPath)) {
    const text = readFileSync(target.rcPath, "utf8");
    const startIdx = text.indexOf(MARKER_START);
    if (startIdx !== -1) {
      const endIdx = text.indexOf(MARKER_END, startIdx);
      if (endIdx !== -1) {
        const head = text.slice(0, startIdx).replace(/\n+$/, "\n");
        const tail = text.slice(endIdx + MARKER_END.length).replace(/^\n+/, "");
        writeFileSync(target.rcPath, `${head}${tail}`, "utf8");
        rcUpdated = true;
      }
    }
  }
  return { shell, scriptPath: target.scriptPath, removedScript, rcUpdated };
}

export { MARKER_START, MARKER_END };
